import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import { HeaderPage } from "@/components/Header";
import FooterPage from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";
import { UserProvider } from "./context/UserContext";
import ScrollToTop from "@/components/ScrollToTop";

const beVietNamPro = Be_Vietnam_Pro({
  variable: "--font-be-vietnam-pro",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Online Course E-Learning",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${beVietNamPro.variable} antialiased`}>
        <UserProvider>
          <HeaderPage />
          <section className=" min-h-screen w-full">{children}</section>
          <FooterPage />
          <Toaster position="top-right" richColors />
          <ScrollToTop />
        </UserProvider>
      </body>
    </html>
  );
}
